pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: npm install
  displayName: 'Install packages'
- script: npm run build:prod
  displayName: 'Build app'
- task: CopyFiles@2
  inputs:
    contents: |
      dist/**
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'conversions-app'
