pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: npm install
  displayName: 'Install packages'
- script: npm run build:prod
  displayName: 'Build app'
- task: PublishBuildArtifacts@1
  inputs:
    #pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #artifactName: 'conversions-app'
    #publishLocation: 'Azure Artifacts'
