version: '3'
services:
  conversions:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: conversions
    networks:
      - conversions
    ports:
      - '8989:8989'
    environment:
     - HOST=0.0.0.0
    command: npm run start
networks:
  conversions:
    driver: bridge
